CHAPTERS = [
    {
        "id": "liczby",
        "label": "Liczby i działania",
        "tagline": "Język Liczb",
        "emoji": "🔢",
        "color": "#06b6d4",
        "glow": "rgba(6,182,212,.5)",
        "gradient": "linear-gradient(135deg,#0e4f6b,#0e7490)",
        "topics": [
            "Liczby i działania",
            "Zbiory liczbowe",
            "Ułamki",
            "Procenty",
            "Potęgowanie i pierwiastkowanie",
            "Wartość bezwzględna",
            "Logarytmy",
        ],
        "map_pos": [1, 1],
    },
    {
        "id": "algebra",
        "label": "Algebra",
        "tagline": "Jak znaleźć ten x...",
        "emoji": "✏️",
        "color": "#a78bfa",
        "glow": "rgba(167,139,250,.5)",
        "gradient": "linear-gradient(135deg,#3b1f6e,#5a2b82)",
        "topics": [
            "Wyrażenia algebraiczne",
            "Równania i nierówności",
            "Układy równań",
            "Wielomiany",
        ],
        "map_pos": [2, 2],
    },
    {
        "id": "funkcje",
        "label": "Funkcje",
        "tagline": "Kreatywne rysowanie linii",
        "emoji": "📈",
        "color": "#10b981",
        "glow": "rgba(16,185,129,.5)",
        "gradient": "linear-gradient(135deg,#065f46,#059669)",
        "topics": [
            "Funkcje (pojęcie funkcji)",
            "Funkcja liniowa",
            "Funkcja kwadratowa",
            "Funkcja wymierna",
            "Funkcja wykładnicza",
            "Funkcja logarytmiczna",
        ],
        "map_pos": [4, 1],
    },
    {
        "id": "ciagi",
        "label": "Ciągi i analiza matematyczna",
        "tagline": "To się powtarza",
        "emoji": "🔁",
        "color": "#fbbf24",
        "glow": "rgba(251,191,36,.5)",
        "gradient": "linear-gradient(135deg,#78350f,#d97706)",
        "topics": [
            "Ciągi",
            "Elementy analizy matematycznej",
        ],
        "map_pos": [4, 4],
    },
    {
        "id": "trygonometria",
        "label": "Trygonometria",
        "tagline": "Skąd tu te wszystkie kąty?",
        "emoji": "📐",
        "color": "#f97316",
        "glow": "rgba(249,115,22,.5)",
        "gradient": "linear-gradient(135deg,#7c2d12,#ea580c)",
        "topics": [
            "Trygonometria",
            "Trygonometria2",
        ],
        "map_pos": [3, 6],
    },
    {
        "id": "geometria",
        "label": "Geometria",
        "tagline": "Kreatywne rysowanie kształtów",
        "emoji": "🔷",
        "color": "#ec4899",
        "glow": "rgba(236,72,153,.5)",
        "gradient": "linear-gradient(135deg,#831843,#db2777)",
        "topics": [
            "Geometria analityczna",
            "Geometria płaska",
            "Geometria przestrzenna",
        ],
        "map_pos": [2, 5],
    },
    {
        "id": "kombinatoryka",
        "label": "Kombinatoryka, prawdopodobieństwo i statystyka",
        "tagline": "Ile dostaniesz wisienek na deser?",
        "emoji": "🍒",
        "color": "#7c3aed",
        "glow": "rgba(124,58,237,.5)",
        "gradient": "linear-gradient(135deg,#4c1d95,#6d28d9)",
        "topics": [
            "Kombinatoryka",
            "Rachunek prawdopodobieństwa",
            "Statystyka",
        ],
        "map_pos": [1, 7],
    },
]

CHAPTERS_BY_ID = {ch["id"]: ch for ch in CHAPTERS}
